apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yml
- service.yml

configMapGenerator:
- files:
  - ca.pub
  name: public-key-config
- files:
  - startup.sh
  name: startup-script-config

generatorOptions:
  disableNameSuffixHash: true
  labels:
    app: ubuntu-ssh